import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import "../globals.css";
import { ThemeProvider } from "@/context/ThemeContext";
import Navbar from "@/components/Navbar";

import { PageProvider } from "@/context/PageContext";
import Footer from "@/components/Footer";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable}  antialiased bg-gray-100 text-gray-900`}
      >
        {/* Navigation Bar */}
        <ThemeProvider>
      <Navbar/>

        {/* Main Content */}
        <main className="max-w-4xl mx-auto p-6">
       <PageProvider>
            {children}
            </PageProvider>
    
          </main>
          </ThemeProvider>

        {/* Footer */}
        
        <Footer/>
      </body>
    </html>
  );
}
